//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ploidulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ploidulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than two alleles at a position impossible .
        /// </summary>
        internal static string ALLELE_COUNT_ERROR {
            get {
                return ResourceManager.GetString("ALLELE_COUNT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAD.
        /// </summary>
        internal static string BAD_CLUSTER {
            get {
                return ResourceManager.GetString("BAD_CLUSTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of clusters detected from input file header: .
        /// </summary>
        internal static string CLUSTER_COUNT_DISPLAY {
            get {
                return ResourceManager.GetString("CLUSTER_COUNT_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing on command line:.
        /// </summary>
        internal static string COMMAND_LINE_INSTRUCTION {
            get {
                return ResourceManager.GetString("COMMAND_LINE_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining output file header and body.
        /// </summary>
        internal static string CONSTRUCTING_OUTPUT_FILE {
            get {
                return ResourceManager.GetString("CONSTRUCTING_OUTPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining output file header and body (finished).
        /// </summary>
        internal static string CONSTRUCTING_OUTPUT_FILE_FINISHED {
            get {
                return ResourceManager.GetString("CONSTRUCTING_OUTPUT_FILE_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is already open.
        /// </summary>
        internal static string FILE_NOT_CLOSED {
            get {
                return ResourceManager.GetString("FILE_NOT_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not opened. Please call Open method  to open the file..
        /// </summary>
        internal static string FILE_NOT_OPENED {
            get {
                return ResourceManager.GetString("FILE_NOT_OPENED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be read.
        /// </summary>
        internal static string FILE_NOT_READABLE {
            get {
                return ResourceManager.GetString("FILE_NOT_READABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINISHED.
        /// </summary>
        internal static string FINISHED {
            get {
                return ResourceManager.GetString("FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished writing to metric summary files.
        /// </summary>
        internal static string FINISHED_WRITING_METRIC {
            get {
                return ResourceManager.GetString("FINISHED_WRITING_METRIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string GENERAL_WARNING {
            get {
                return ResourceManager.GetString("GENERAL_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOD.
        /// </summary>
        internal static string GOOD_CLUSTER {
            get {
                return ResourceManager.GetString("GOOD_CLUSTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler has finished processing sequences.
        /// </summary>
        internal static string HANDLER_FINISHED {
            get {
                return ResourceManager.GetString("HANDLER_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haplotype count indicates cluster is not good: .
        /// </summary>
        internal static string HAPLOTYPE_COUNT_BAD {
            get {
                return ResourceManager.GetString("HAPLOTYPE_COUNT_BAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dictionary key.
        /// </summary>
        internal static string INVALID_KEY {
            get {
                return ResourceManager.GetString("INVALID_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have selected a valid BAM file for input and have nominated the population size.
        /// </summary>
        internal static string MANDATORY_FIELDS_WARNING {
            get {
                return ResourceManager.GetString("MANDATORY_FIELDS_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory fields.
        /// </summary>
        internal static string MANDATORY_FIELDS_WARNING_HEADER {
            get {
                return ResourceManager.GetString("MANDATORY_FIELDS_WARNING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .metr.
        /// </summary>
        internal static string METRIC_FILEEXTENSION {
            get {
                return ResourceManager.GetString("METRIC_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        internal static string METRIC_NAME {
            get {
                return ResourceManager.GetString("METRIC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes an IMetric or List&lt;IMetric&gt; to a particular location, usually a file. The output is a tab separated text file with a .metr file extension.
        /// </summary>
        internal static string METRICFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("METRICFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to calculate genotypes. Please close any related files then try again..
        /// </summary>
        internal static string PHASE_ERROR_DELETE {
            get {
                return ResourceManager.GetString("PHASE_ERROR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing PHASE.exe.
        /// </summary>
        internal static string PHASE_ERROR_EXECUTING {
            get {
                return ResourceManager.GetString("PHASE_ERROR_EXECUTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHASE was not properly terminated. Please terminate the PHASE.exe process then try again..
        /// </summary>
        internal static string PHASE_IMPROPERLY_TERMINATED {
            get {
                return ResourceManager.GetString("PHASE_IMPROPERLY_TERMINATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser/processer thread must pause to let bam writer thread catch up.
        /// </summary>
        internal static string PROCESSING_THREAD_PAUSED {
            get {
                return ResourceManager.GetString("PROCESSING_THREAD_PAUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is currently being output to file. If you close this window the output file will be incomplete.Are you sure you want to close this window?.
        /// </summary>
        internal static string WINDOW_CLOSE_WARNING {
            get {
                return ResourceManager.GetString("WINDOW_CLOSE_WARNING", resourceCulture);
            }
        }
    }
}
